(package "flymake-languagetool"
         "0.2.0"
         "Flymake support for LanguageTool")

(website-url "https://github.com/emacs-languagetool/flymake-languagetool")
(keywords "grammar" "check")

(package-file "flymake-languagetool.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "27.1")
(depends-on "s")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
